language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - cd ..
  - curl -O -L http://downloads.sourceforge.net/project/pyqt/sip/sip-4.13.3/sip-4.13.3.tar.gz
  - tar -xvf sip-4.13.3.tar.gz
  - cd sip-4.13.3
  - python configure.py
  - make -j 4
  - sudo make install
  - cd ..
  - curl -O -L http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.9.4/PyQt-x11-gpl-4.9.4.tar.gz
  - tar -xvf PyQt-x11-gpl-4.9.4.tar.gz
  - cd PyQt-x11-gpl-4.9.4
  - python configure.py --confirm-license
  - make -j 4
  - sudo make install
  - cd ../sIBL_GUI
install:
  - pip install Umbra
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: nosetests -I "^tests.py$|testsInternational"